Pull down the Postgres container on bootstrap
It's kinda big, so not having to pull it down during the test run is
nice, so we don't hit timeouts from pulling containers.

Did this because I thought some container problems with Colima was
because getting containers were slow. It wasn't, but decided to keep it
because it's still nice when I had figured out the container to make
the wrapping was easy.

diff --git a/script/bootstrap b/script/bootstrap
--- a/script/bootstrap
+++ b/script/bootstrap
@@ -61,6 +61,25 @@ go install -tags='no_clickhouse no_libsql no_mssql no_mysql no_vertica no_xflag 
 ## Install playwright dependencies
 go run ./cmd/local-dev-dependencies/ playwright
 
+function get-container() {
+  local variable_name="$1"
+  local file="$2"
+
+  echo "Pulling $variable_name..."
+
+  # assumption: we're going to put all the containers in a file, split by =, remove quotes and extra spacing for a clean container name.
+  container_name=$(grep "${variable_name} = " "${file}" | cut -d'=' -f2 | sed -E 's/[" ]//g')
+
+  # Try to pull down the container or fail if the pull fails.
+  if ! docker pull "${container_name}"; then
+    echo "Failed to pull down postgres container" >&2
+    exit 1
+  fi
+}
+
+## Download required testcontainer dependency containers
+get-container "PostgresContainer" "test/postgres.go"
+
 ## Always finish with go mod tidy
 # In case we get something nasty when installing everything it'll try and sort it out,
 # and because I was getting incompatible dependencies when installing the cli tools before,
